import { NextResponse } from "next/server";
import { and, eq } from "drizzle-orm";
import { db } from "@/db/client";
import { backlinks, clients } from "@/db/schema";

export const dynamic = "force-dynamic";

export async function GET(request: Request) {
  const url = new URL(request.url);
  const clientIdParam =
    url.searchParams.get("client") ?? url.searchParams.get("clientId");
  const clientId = clientIdParam ? Number(clientIdParam) : null;

  const where = clientId
    ? and(
        eq(backlinks.status, "disavow"),
        eq(backlinks.clientId, clientId),
      )
    : eq(backlinks.status, "disavow");

  const rows = await db
    .select({
      sourceUrl: backlinks.sourceUrl,
      sourceDomain: backlinks.sourceDomain,
      anchorText: backlinks.anchorText,
      notes: backlinks.notes,
      clientName: clients.name,
    })
    .from(backlinks)
    .leftJoin(clients, eq(backlinks.clientId, clients.id))
    .where(where);

  // Group by domain (Google's disavow file is most useful per-domain)
  const domains = new Map<string, typeof rows>();
  for (const r of rows) {
    const list = domains.get(r.sourceDomain) ?? [];
    list.push(r);
    domains.set(r.sourceDomain, list);
  }

  const lines: string[] = [
    "# Google Disavow file generated by SEO tool",
    `# Generated: ${new Date().toISOString()}`,
    `# ${rows.length} entries across ${domains.size} domains`,
    "#",
    "# Submit at: https://search.google.com/search-console/disavow-links-tool",
    "# Only use this if you've identified clearly spammy/manipulative links.",
    "# Most modern sites should NOT submit a disavow file unless under manual action.",
    "",
  ];

  // Sort domains alphabetically for stable output
  const sorted = Array.from(domains.entries()).sort(([a], [b]) =>
    a.localeCompare(b),
  );

  for (const [domain, links] of sorted) {
    if (links[0]?.notes) {
      lines.push(`# ${links[0].notes.replace(/[\r\n]+/g, " ")}`);
    }
    lines.push(`domain:${domain}`);
    lines.push("");
  }

  const filename = clientId
    ? `disavow-client-${clientId}.txt`
    : `disavow-all.txt`;

  return new NextResponse(lines.join("\n"), {
    status: 200,
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Content-Disposition": `attachment; filename="${filename}"`,
    },
  });
}
