<?php
/**
 * Plugin Name: SEO Tool Bridge
 * Plugin URI: https://github.com/mohisnrazaac/All-In-One-Free-SEO-Tool
 * Description: Connects this WordPress site to the self-hosted SEO Tool by DiceCodes. Lets the tool read + write meta titles, descriptions, alt text, schema, internal links, and create posts — with full revision history and one-click undo. Compatible with Yoast / Rank Math / All in One SEO.
 * Version: 0.4.0
 * Requires at least: 6.0
 * Tested up to: 6.7
 * Requires PHP: 8.0
 * Author: DiceCodes
 * Author URI: https://dicecodes.com
 * License: MIT
 * License URI: https://opensource.org/licenses/MIT
 * Text Domain: seo-tool-bridge
 *
 * Architecture: a single connection key (generated by this plugin, pasted into
 * SEO Tool settings) authenticates inbound REST requests. Every write is
 * logged + the previous value is saved as a revision so the SEO Tool can
 * offer one-click undo per CLAUDE.md §3.5.
 *
 * The licence here must stay in step with the repository's LICENSE file,
 * which is MIT. It said PolyForm Noncommercial, left over from before the
 * project relicensed — which mattered for more than tidiness: PolyForm is
 * not GPL-compatible, and WordPress.org only accepts GPLv2-or-later
 * compatible plugins. As labelled, this could never have been submitted
 * to the directory it was written to be published in. MIT is compatible.
 */

if (!defined('ABSPATH')) {
    exit;
}

define('STB_VERSION', '0.4.0');
define('STB_OPTION_KEY', 'stb_connection_key');
define('STB_OPTION_REVISIONS', 'stb_revisions');
define('STB_REST_NAMESPACE', 'seo-tool/v1');

// =====================
// Setup + key generation
// =====================

register_activation_hook(__FILE__, function () {
    if (!get_option(STB_OPTION_KEY)) {
        update_option(STB_OPTION_KEY, wp_generate_password(48, false, false));
    }
    if (get_option(STB_OPTION_REVISIONS) === false) {
        update_option(STB_OPTION_REVISIONS, []);
    }
});

// =====================
// Settings page (Tools menu)
// =====================

add_action('admin_menu', function () {
    add_management_page(
        __('SEO Tool Bridge', 'seo-tool-bridge'),
        __('SEO Tool Bridge', 'seo-tool-bridge'),
        'manage_options',
        'seo-tool-bridge',
        'stb_render_admin_page'
    );
});

function stb_render_admin_page(): void
{
    if (!current_user_can('manage_options')) {
        return;
    }

    if (
        isset($_POST['stb_regenerate']) &&
        check_admin_referer('stb_regenerate_action', 'stb_nonce')
    ) {
        update_option(STB_OPTION_KEY, wp_generate_password(48, false, false));
        echo '<div class="updated notice"><p>New connection key generated. Update it in the SEO Tool settings.</p></div>';
    }

    $key = get_option(STB_OPTION_KEY);
    $rest_url = rest_url(STB_REST_NAMESPACE);
    ?>
    <div class="wrap">
        <h1>SEO Tool Bridge</h1>
        <p>Connects this WordPress site to your self-hosted SEO Tool, so AI suggestions can be applied with one click instead of copy-paste.</p>

        <h2>Connection details</h2>
        <table class="form-table">
            <tr>
                <th scope="row"><label>REST endpoint</label></th>
                <td>
                    <input type="text" readonly value="<?php echo esc_attr($rest_url); ?>" class="regular-text" onclick="this.select()" />
                    <p class="description">Paste this into SEO Tool → Settings → CMS connections.</p>
                </td>
            </tr>
            <tr>
                <th scope="row"><label>Connection key</label></th>
                <td>
                    <input type="text" readonly value="<?php echo esc_attr($key); ?>" class="regular-text" onclick="this.select()" />
                    <p class="description">Treat this like a password. Anyone with the key can edit your site's SEO settings.</p>
                </td>
            </tr>
        </table>

        <form method="post">
            <?php wp_nonce_field('stb_regenerate_action', 'stb_nonce'); ?>
            <p>
                <button type="submit" name="stb_regenerate" class="button button-secondary"
                        onclick="return confirm('Regenerate the key? The old key will stop working immediately.');">
                    Regenerate key
                </button>
            </p>
        </form>

        <h2>What this plugin can do</h2>
        <ul style="list-style: disc; margin-left: 20px;">
            <li>Read + write the post / page / product title</li>
            <li>Read + write the meta description (Yoast / Rank Math / All in One SEO compatible — writes to all three so it sticks regardless of which is active)</li>
            <li>Read + write image alt text in the Media Library</li>
            <li>List the images on a post with their attachment IDs — this is what lets the SEO Tool actually fix missing alt text, rather than only report it</li>
            <li>Read + write JSON-LD schema markup, injected into &lt;head&gt; on singular pages</li>
            <li>Insert internal links into post content, first match only, never inside an existing link, heading or code block</li>
            <li>List + look up posts by URL (used by the SEO Tool's one-click fix flow)</li>
            <li>Create new posts (draft or published) — used by the daily AI agent</li>
            <li>Full revision log with one-click undo on every change, including a whole-body restore for content edits</li>
        </ul>
        <p style="color: #666; font-size: 12px;">
            Redirects + robots.txt management are not here yet. Internal linking
            edits post content — if you'd rather it didn't, leave the SEO Tool's
            autonomy on &ldquo;suggest only&rdquo; and approve each change yourself.
        </p>

        <h2>Recent changes</h2>
        <?php stb_render_revisions(); ?>
    </div>
    <?php
}

function stb_render_revisions(): void
{
    $revisions = get_option(STB_OPTION_REVISIONS, []);
    if (empty($revisions)) {
        echo '<p>No changes applied yet.</p>';
        return;
    }
    echo '<table class="widefat striped" style="max-width: 900px;">';
    echo '<thead><tr><th>When</th><th>Field</th><th>Object</th><th>Old → New</th></tr></thead><tbody>';
    foreach (array_slice(array_reverse($revisions), 0, 30) as $r) {
        printf(
            '<tr><td>%s</td><td>%s</td><td>%s</td><td><code>%s</code> → <code>%s</code></td></tr>',
            // wp_date, not date: revisions are timestamped with time(),
            // and date() renders them in the SERVER's timezone. On the
            // managed hosts most of these sites run on that is UTC, so
            // a change made at 9am local read as 4am to the person who
            // made it — in the one table they'd check to work out
            // whether the tool had touched their site.
            esc_html(wp_date('Y-m-d H:i', (int)$r['ts'])),
            esc_html($r['field']),
            esc_html($r['object']),
            esc_html(mb_substr((string)($r['old'] ?? ''), 0, 80)),
            esc_html(mb_substr((string)($r['new'] ?? ''), 0, 80))
        );
    }
    echo '</tbody></table>';
}

// =====================
// REST API
// =====================

add_action('rest_api_init', function () {
    register_rest_route(STB_REST_NAMESPACE, '/ping', [
        'methods'  => 'GET',
        'callback' => 'stb_rest_ping',
        'permission_callback' => 'stb_check_key',
    ]);

    // Single route, two methods. Calling register_rest_route twice with
    // the same path made WP's REST router behavior depend on call order
    // — the second call would shadow the first, breaking GET. Passing
    // an array of method configs is the documented WP way.
    register_rest_route(STB_REST_NAMESPACE, '/post/(?P<id>\d+)/seo', [
        [
            'methods'  => 'GET',
            'callback' => 'stb_rest_get_post_seo',
            'permission_callback' => 'stb_check_key',
            'args' => ['id' => ['validate_callback' => static fn($v) => is_numeric($v)]],
        ],
        [
            'methods'  => 'POST',
            'callback' => 'stb_rest_update_post_seo',
            'permission_callback' => 'stb_check_key',
            'args' => ['id' => ['validate_callback' => static fn($v) => is_numeric($v)]],
        ],
    ]);

    register_rest_route(STB_REST_NAMESPACE, '/attachment/(?P<id>\d+)/alt', [
        'methods'  => 'POST',
        'callback' => 'stb_rest_update_alt',
        'permission_callback' => 'stb_check_key',
        'args' => ['id' => ['validate_callback' => static fn($v) => is_numeric($v)]],
    ]);

    // GET added in 0.3.0. Without a read, the SEO Tool could only write
    // schema to pages that had none — writing to a page with existing
    // markup would destroy hand-written structured data with no way back,
    // so the tool refused to try. Reading first makes updates safe.
    register_rest_route(STB_REST_NAMESPACE, '/post/(?P<id>\d+)/schema', [
        [
            'methods'  => 'GET',
            'callback' => 'stb_rest_get_schema',
            'permission_callback' => 'stb_check_key',
            'args' => ['id' => ['validate_callback' => static fn($v) => is_numeric($v)]],
        ],
        [
            'methods'  => 'POST',
            'callback' => 'stb_rest_set_schema',
            'permission_callback' => 'stb_check_key',
            'args' => ['id' => ['validate_callback' => static fn($v) => is_numeric($v)]],
        ],
    ]);

    // 0.3.0 — the images on a post, WITH their attachment ids.
    //
    // /attachment/{id}/alt has always existed, but nothing could work out
    // which attachment an image on a page belonged to: an audit finding
    // gives a page URL and an <img src>, not an id. So the SEO Tool could
    // find images missing alt text and never fix one. This closes that.
    register_rest_route(STB_REST_NAMESPACE, '/post/(?P<id>\d+)/images', [
        'methods'  => 'GET',
        'callback' => 'stb_rest_list_post_images',
        'permission_callback' => 'stb_check_key',
        'args' => ['id' => ['validate_callback' => static fn($v) => is_numeric($v)]],
    ]);

    // 0.3.0 — insert internal links into post content.
    //
    // This is the only endpoint that edits the post BODY rather than a
    // metadata field, which makes it a different risk class: a bad write
    // damages the article itself. Three guards, all in the handler:
    // anchors are matched only in visible text (never inside an existing
    // tag or link), the first occurrence only, and the whole prior
    // post_content is stored as the revision so undo is exact.
    register_rest_route(STB_REST_NAMESPACE, '/post/(?P<id>\d+)/links', [
        'methods'  => 'POST',
        'callback' => 'stb_rest_insert_links',
        'permission_callback' => 'stb_check_key',
        'args' => ['id' => ['validate_callback' => static fn($v) => is_numeric($v)]],
    ]);

    register_rest_route(STB_REST_NAMESPACE, '/posts/list', [
        'methods'  => 'GET',
        'callback' => 'stb_rest_list_posts',
        'permission_callback' => 'stb_check_key',
    ]);

    // Resolve a public URL to a post ID. Used by the SEO Tool's
    // one-click fix flow so users only need a URL, not the post ID.
    register_rest_route(STB_REST_NAMESPACE, '/find', [
        'methods'  => 'GET',
        'callback' => 'stb_rest_find_by_url',
        'permission_callback' => 'stb_check_key',
        'args' => ['url' => ['validate_callback' => fn($v) => is_string($v) && strlen($v) > 3]],
    ]);

    register_rest_route(STB_REST_NAMESPACE, '/revisions', [
        'methods'  => 'GET',
        'callback' => 'stb_rest_revisions',
        'permission_callback' => 'stb_check_key',
    ]);

    register_rest_route(STB_REST_NAMESPACE, '/undo/(?P<rev_id>\d+)', [
        'methods'  => 'POST',
        'callback' => 'stb_rest_undo',
        'permission_callback' => 'stb_check_key',
        'args' => ['rev_id' => ['validate_callback' => static fn($v) => is_numeric($v)]],
    ]);

    // v0.2.0+ — create a post. Used by daily automation when a blog_draft
    // queue item is approved + published. Status defaults to "draft" so
    // the WP editor gets a final pass before going live; schedules with
    // auto_publish=true pass "publish" to skip that.
    register_rest_route(STB_REST_NAMESPACE, '/posts', [
        'methods'  => 'POST',
        'callback' => 'stb_rest_create_post',
        'permission_callback' => 'stb_check_key',
    ]);
});

/**
 * Authenticate an inbound request against the connection key.
 *
 * Accepts the key in EITHER header:
 *
 *   X-STB-Key: <key>                 preferred
 *   Authorization: Bearer <key>      also accepted
 *
 * This only read `Authorization`, and the SEO Tool has only ever sent
 * `X-STB-Key` — so every request from the tool to this plugin returned
 * 401, for every endpoint, for the plugin's entire life. Nothing about
 * the failure said "wrong header": a 401 reads as a bad key, which is
 * what anyone debugging it would have chased.
 *
 * X-STB-Key is preferred rather than merely tolerated, because Apache
 * with mod_php commonly drops the Authorization header before PHP sees
 * it unless the site owner adds a rewrite rule. A custom header has no
 * such problem, so the tool's choice was the better one. Bearer stays
 * supported for anything already built against the documented form.
 *
 * hash_equals is timing-safe; the length check in front of it is not a
 * security property, just an early out.
 */
function stb_check_key(WP_REST_Request $req): bool
{
    $expected = get_option(STB_OPTION_KEY);
    if (!is_string($expected) || $expected === '') {
        return false;
    }

    $custom = trim((string)($req->get_header('x-stb-key') ?? ''));
    if ($custom !== '' && hash_equals($expected, $custom)) {
        return true;
    }

    $auth = (string)($req->get_header('authorization') ?? '');
    if ($auth === '') {
        return false;
    }
    $bearer = trim((string)preg_replace('/^Bearer\s+/i', '', $auth));
    return $bearer !== '' && hash_equals($expected, $bearer);
}

function stb_rest_ping(): WP_REST_Response
{
    return new WP_REST_Response([
        'ok' => true,
        'plugin_version' => STB_VERSION,
        'wp_version' => get_bloginfo('version'),
        'site_url' => home_url(),
        // What this plugin can actually do. `redirects` was listed here
        // and true, and no redirect route has ever been registered —
        // nothing read the field yet, so it was a lie waiting to be
        // believed. Anything added here must have a route above it.
        'capabilities' => [
            'meta_titles' => true,
            'meta_descriptions' => true,
            'image_alt' => true,
            'schema' => true,
            'internal_links' => true,
            'create_posts' => true,
            'redirects' => false,
            'canonical' => false,
            'robots' => false,
        ],
    ]);
}

function stb_get_meta_description(int $post_id): string
{
    // Try the SEO plugins in priority order
    $candidates = [
        '_yoast_wpseo_metadesc',          // Yoast
        'rank_math_description',           // Rank Math
        '_aioseop_description',            // All in One SEO (legacy)
        '_aioseo_description',             // All in One SEO (current)
    ];
    foreach ($candidates as $key) {
        $val = get_post_meta($post_id, $key, true);
        if (!empty($val)) {
            return (string)$val;
        }
    }
    return '';
}

function stb_set_meta_description(int $post_id, string $value): void
{
    // Write to all known plugins so it sticks regardless of which one is active
    update_post_meta($post_id, '_yoast_wpseo_metadesc', $value);
    update_post_meta($post_id, 'rank_math_description', $value);
    update_post_meta($post_id, '_aioseo_description', $value);
}

function stb_record_revision(string $field, string $object, $old, $new): int
{
    $revs = get_option(STB_OPTION_REVISIONS, []);

    // Monotonic, taken from the highest id ever issued — NOT count() + 1.
    //
    // The list is capped at the most recent 500, so once a site passed
    // 500 changes count() stayed at 500 and every revision from then on
    // was id 501. /undo/501 then found the OLDEST 501 and restored a
    // value from hundreds of edits ago, to a live site, reporting
    // success. A busy site would hit this in a week.
    $highest = 0;
    foreach ($revs as $r) {
        $id = (int)($r['rev_id'] ?? 0);
        if ($id > $highest) {
            $highest = $id;
        }
    }
    $rev_id = $highest + 1;

    $revs[] = [
        'rev_id' => $rev_id,
        'ts' => time(),
        'field' => $field,
        'object' => $object,
        'old' => $old,
        'new' => $new,
    ];
    // Cap at last 500 to keep options table small
    if (count($revs) > 500) {
        $revs = array_slice($revs, -500);
    }
    update_option(STB_OPTION_REVISIONS, $revs);
    return $rev_id;
}

function stb_rest_get_post_seo(WP_REST_Request $req): WP_REST_Response
{
    $id = (int)$req['id'];
    $post = get_post($id);
    if (!$post) {
        return new WP_REST_Response(['ok' => false, 'error' => 'Post not found'], 404);
    }
    return new WP_REST_Response([
        'ok' => true,
        'id' => $id,
        'title' => $post->post_title,
        'meta_description' => stb_get_meta_description($id),
        'permalink' => get_permalink($id),
        'status' => $post->post_status,
        'modified' => $post->post_modified,
    ]);
}

function stb_rest_update_post_seo(WP_REST_Request $req): WP_REST_Response
{
    $id = (int)$req['id'];
    $post = get_post($id);
    if (!$post) {
        return new WP_REST_Response(['ok' => false, 'error' => 'Post not found'], 404);
    }
    $body = $req->get_json_params() ?: [];
    $changes = [];

    if (isset($body['title'])) {
        $new = sanitize_text_field($body['title']);
        $old = $post->post_title;
        if ($new !== $old) {
            wp_update_post(['ID' => $id, 'post_title' => $new]);
            $rev_id = stb_record_revision('title', "post:$id", $old, $new);
            $changes[] = ['field' => 'title', 'rev_id' => $rev_id];
        }
    }

    if (isset($body['meta_description'])) {
        $new = sanitize_text_field($body['meta_description']);
        $old = stb_get_meta_description($id);
        if ($new !== $old) {
            stb_set_meta_description($id, $new);
            $rev_id = stb_record_revision('meta_description', "post:$id", $old, $new);
            $changes[] = ['field' => 'meta_description', 'rev_id' => $rev_id];
        }
    }

    return new WP_REST_Response(['ok' => true, 'changes' => $changes]);
}

function stb_rest_update_alt(WP_REST_Request $req): WP_REST_Response
{
    $id = (int)$req['id'];
    $post = get_post($id);
    if (!$post || $post->post_type !== 'attachment') {
        return new WP_REST_Response(['ok' => false, 'error' => 'Attachment not found'], 404);
    }
    $body = $req->get_json_params() ?: [];
    $new = isset($body['alt']) ? sanitize_text_field($body['alt']) : '';
    $old = (string)get_post_meta($id, '_wp_attachment_image_alt', true);
    if ($new !== $old) {
        update_post_meta($id, '_wp_attachment_image_alt', $new);
        $rev_id = stb_record_revision('alt', "attachment:$id", $old, $new);
        return new WP_REST_Response(['ok' => true, 'rev_id' => $rev_id]);
    }
    return new WP_REST_Response(['ok' => true, 'rev_id' => null, 'note' => 'no change']);
}

function stb_rest_set_schema(WP_REST_Request $req): WP_REST_Response
{
    $id = (int)$req['id'];
    $body = $req->get_json_params() ?: [];
    // IMPORTANT: do NOT run wp_kses_post() on JSON-LD. It's an HTML
    // sanitizer that strips characters that are legitimate inside JSON
    // string values (<, >, &), producing invalid JSON. Instead, validate
    // that the input is well-formed JSON via json_decode().
    $jsonld_raw = isset($body['jsonld']) ? (string)$body['jsonld'] : '';

    // Empty means REMOVE the markup, and must not be an error.
    //
    // The only audit finding that triggers a schema write is
    // missing_schema, so the previous value the SEO Tool records is
    // always the empty string — and undo replays that previous value.
    // Rejecting it meant the tool could add structured data to a page
    // and then had no way to take it off again, while its own rule is
    // that it never writes anything it can't undo.
    //
    // Deletes the meta rather than storing '' so the front-end filter
    // that prints the <script> tag sees nothing at all.
    if ($jsonld_raw === '') {
        $old = (string)get_post_meta($id, '_stb_schema_jsonld', true);
        if ($old === '') {
            return new WP_REST_Response(['ok' => true, 'rev_id' => null, 'note' => 'no change']);
        }
        delete_post_meta($id, '_stb_schema_jsonld');
        $rev_id = stb_record_revision('schema', "post:$id", $old, '');
        return new WP_REST_Response(['ok' => true, 'rev_id' => $rev_id, 'removed' => true]);
    }

    $decoded = json_decode($jsonld_raw, true);
    if ($decoded === null) {
        // Both branches end up here, and both are handled above or
        // rejected here — deliberately, because the old code let the
        // literal string "null" through as "valid JSON". It is, but
        // wp_json_encode(null) is "null", which is not empty, so the
        // head filter printed <script type="application/ld+json">null
        // </script> onto the page: markup that validators reject and
        // that makes the page look marked up when it isn't.
        if (strtolower(trim($jsonld_raw)) === 'null') {
            return new WP_REST_Response(
                [
                    'ok' => false,
                    'error' => 'jsonld cannot be null — send an empty string to remove the markup instead',
                ],
                400,
            );
        }
        return new WP_REST_Response(
            ['ok' => false, 'error' => 'jsonld must be valid JSON'],
            400,
        );
    }

    // Scalars decode fine and are not structured data. "42" or "\"hi\""
    // would be stored and printed as a JSON-LD block that means nothing.
    if (!is_array($decoded)) {
        return new WP_REST_Response(
            ['ok' => false, 'error' => 'jsonld must be a JSON object or array'],
            400,
        );
    }
    // Re-encode for canonical form, also flags edge-case unicode.
    $jsonld = wp_json_encode($decoded, JSON_UNESCAPED_SLASHES);
    if ($jsonld === false) {
        return new WP_REST_Response(
            ['ok' => false, 'error' => 'jsonld could not be re-encoded'],
            400,
        );
    }
    $old = (string)get_post_meta($id, '_stb_schema_jsonld', true);
    update_post_meta($id, '_stb_schema_jsonld', $jsonld);
    $rev_id = stb_record_revision('schema', "post:$id", $old, $jsonld);
    return new WP_REST_Response(['ok' => true, 'rev_id' => $rev_id]);
}

/**
 * Read the JSON-LD we previously wrote for a post.
 *
 * Returns only markup this plugin manages — schema output by Yoast,
 * Rank Math or a theme is deliberately NOT reported, because the SEO
 * Tool uses this to decide whether it may overwrite, and claiming
 * ownership of another plugin's markup would let it destroy that.
 *
 * An empty string means "we have written none", not "this page has
 * none". The distinction matters and the field name says so.
 */
function stb_rest_get_schema(WP_REST_Request $req): WP_REST_Response
{
    $id = (int)$req['id'];
    if (!get_post($id)) {
        return new WP_REST_Response(['ok' => false, 'error' => 'No such post'], 404);
    }
    return new WP_REST_Response([
        'ok' => true,
        'managedJsonLd' => (string)get_post_meta($id, '_stb_schema_jsonld', true),
    ]);
}

/**
 * Every image on a post, with the attachment id needed to set alt text.
 *
 * Two sources, because neither is complete on its own: the media library
 * knows about attachments uploaded to the post, and the content itself
 * knows about images inserted from elsewhere. WordPress marks the latter
 * with a `wp-image-{id}` class, which is how we recover the id for an
 * image the post doesn't "own".
 *
 * Images we can't resolve to an attachment are returned with a null id
 * and reported honestly rather than dropped — the SEO Tool shows them as
 * "found, can't fix automatically" instead of pretending they don't
 * exist.
 */
function stb_rest_list_post_images(WP_REST_Request $req): WP_REST_Response
{
    $id = (int)$req['id'];
    $post = get_post($id);
    if (!$post) {
        return new WP_REST_Response(['ok' => false, 'error' => 'No such post'], 404);
    }

    $images = [];
    $seen = [];

    $add = function (?int $att_id, string $src) use (&$images, &$seen) {
        $key = $att_id ? "id:$att_id" : "src:$src";
        if (isset($seen[$key])) {
            return;
        }
        $seen[$key] = true;
        $images[] = [
            'attachmentId' => $att_id,
            'src' => $src,
            'alt' => $att_id
                ? (string)get_post_meta($att_id, '_wp_attachment_image_alt', true)
                : '',
            // The tool needs to know an id-less image is unfixable rather
            // than merely un-alt-texted.
            'fixable' => $att_id !== null,
        ];
    };

    // Featured image first — it's the one most likely to be missing alt
    // text and the most visible when it is.
    $thumb_id = (int)get_post_thumbnail_id($id);
    if ($thumb_id > 0) {
        $add($thumb_id, (string)wp_get_attachment_url($thumb_id));
    }

    // Attachments uploaded to this post.
    foreach (get_attached_media('image', $id) as $att) {
        $add((int)$att->ID, (string)wp_get_attachment_url($att->ID));
    }

    // Images in the content, including ones from the media library that
    // were never "attached" to this post.
    if (preg_match_all('/<img[^>]+>/i', (string)$post->post_content, $tags)) {
        foreach ($tags[0] as $tag) {
            if (!preg_match('/\ssrc=["\']([^"\']+)["\']/i', $tag, $m)) {
                continue;
            }
            $src = $m[1];
            $att_id = null;
            if (preg_match('/wp-image-(\d+)/', $tag, $cm)) {
                $att_id = (int)$cm[1];
            } else {
                $guess = attachment_url_to_postid($src);
                if ($guess > 0) {
                    $att_id = $guess;
                }
            }
            $add($att_id, $src);
        }
    }

    return new WP_REST_Response(['ok' => true, 'images' => $images]);
}

/**
 * Insert internal links into a post's body.
 *
 * The only endpoint here that edits post_content rather than a metadata
 * field, and it is treated accordingly. A bad write damages the article,
 * not a tag — so:
 *
 *  - Anchors are matched in VISIBLE TEXT ONLY. The content is split on
 *    tags and only the text between them is searched, so an anchor can
 *    never be matched inside an attribute, a URL, a script, or the text
 *    of an existing link. Naive str_replace on HTML would happily turn
 *    `<a href="/x">pricing</a>` into nested anchors and corrupt the
 *    markup.
 *  - First occurrence only, once per anchor. Linking every mention of a
 *    word is the behaviour that gets auto-linking plugins uninstalled.
 *  - Skips anchors already linked anywhere in the post, so re-running
 *    can't stack links on the same phrase.
 *  - The ENTIRE previous post_content is stored as the revision, so undo
 *    restores the article exactly rather than trying to unpick edits.
 */
function stb_rest_insert_links(WP_REST_Request $req): WP_REST_Response
{
    $id = (int)$req['id'];
    $post = get_post($id);
    if (!$post) {
        return new WP_REST_Response(['ok' => false, 'error' => 'No such post'], 404);
    }

    $body = $req->get_json_params() ?: [];
    $links = isset($body['links']) && is_array($body['links']) ? $body['links'] : [];
    if (!$links) {
        return new WP_REST_Response(['ok' => false, 'error' => 'links required'], 400);
    }
    // A cap the caller cannot exceed. Ten new links in one pass is
    // already a lot for one article; more reads as spam to a person and
    // to Google.
    if (count($links) > 10) {
        $links = array_slice($links, 0, 10);
    }

    $original = (string)$post->post_content;
    $content = $original;
    $inserted = [];
    $skipped = [];

    foreach ($links as $link) {
        $anchor = trim((string)($link['anchor'] ?? ''));
        $url = trim((string)($link['url'] ?? ''));
        if ($anchor === '' || $url === '') {
            continue;
        }
        // Only same-site URLs. This endpoint exists for internal linking;
        // letting it write arbitrary external hrefs would turn a
        // connection key into a link-injection vector.
        if (!stb_is_internal_url($url)) {
            $skipped[] = ['anchor' => $anchor, 'reason' => 'not an internal URL'];
            continue;
        }
        if (mb_strlen($anchor) < 3 || mb_strlen($anchor) > 80) {
            $skipped[] = ['anchor' => $anchor, 'reason' => 'anchor length'];
            continue;
        }
        // Already linked somewhere in the post — leave it alone.
        if (stb_anchor_is_linked($content, $anchor)) {
            $skipped[] = ['anchor' => $anchor, 'reason' => 'already linked'];
            continue;
        }

        $replaced = stb_link_first_text_occurrence($content, $anchor, $url);
        if ($replaced === null) {
            $skipped[] = ['anchor' => $anchor, 'reason' => 'anchor not found in visible text'];
            continue;
        }
        $content = $replaced;
        $inserted[] = ['anchor' => $anchor, 'url' => $url];
    }

    if (!$inserted) {
        return new WP_REST_Response([
            'ok' => true,
            'inserted' => [],
            'skipped' => $skipped,
            'changed' => false,
        ]);
    }

    $res = wp_update_post(['ID' => $id, 'post_content' => $content], true);
    if (is_wp_error($res)) {
        return new WP_REST_Response(
            ['ok' => false, 'error' => $res->get_error_message()],
            500,
        );
    }

    // Whole-body revision. Undo restores the article exactly.
    $rev_id = stb_record_revision('content', "post:$id", $original, $content);

    return new WP_REST_Response([
        'ok' => true,
        'inserted' => $inserted,
        'skipped' => $skipped,
        'changed' => true,
        'rev_id' => $rev_id,
    ]);
}

/** Same-host check. Relative paths are internal by definition. */
function stb_is_internal_url(string $url): bool
{
    if (str_starts_with($url, '/') && !str_starts_with($url, '//')) {
        return true;
    }
    $host = parse_url($url, PHP_URL_HOST);
    if (!$host) {
        return false;
    }
    $home = parse_url(home_url(), PHP_URL_HOST);
    return strtolower($host) === strtolower((string)$home);
}

/**
 * Is this anchor phrase already inside a link somewhere in the content?
 *
 * Walks the markup the same way the inserter does, and answers yes only
 * when the phrase appears in text that is genuinely inside an <a>.
 *
 * This used to be two string tests, and both were wrong:
 *
 *   stripos($content, '>' . $anchor . '<')
 *     True for ANY element whose whole text is the phrase —
 *     <code>pricing</code>, <li>pricing</li>, <strong>pricing</strong>,
 *     <td>pricing</td>. So a phrase that appeared in a list or a table
 *     anywhere on the page could never be linked, and the tool answered
 *     "already linked", which was simply untrue. Nothing errored; the
 *     work was silently skipped with a wrong explanation.
 *
 *   preg_match('/<a[^>]*>[^<]*' . preg_quote($anchor) . '/i', ...)
 *     Only sees the phrase in an anchor's FIRST text node, so
 *     <a href="/x"><strong>pricing</strong></a> read as not linked, and
 *     the inserter would have been asked to link it a second time.
 *
 * Walking costs one pass over the content and is right in both
 * directions.
 */
function stb_anchor_is_linked(string $content, string $anchor): bool
{
    $parts = preg_split('/(<[^>]+>)/', $content, -1, PREG_SPLIT_DELIM_CAPTURE);
    if ($parts === false) {
        return false;
    }

    $depth = 0;
    foreach ($parts as $part) {
        if ($part === '') {
            continue;
        }
        if ($part[0] === '<') {
            if (preg_match('/^<\s*(\/?)\s*a\b/i', $part, $m)) {
                $depth += $m[1] === '/' ? -1 : 1;
                if ($depth < 0) {
                    $depth = 0;
                }
            }
            continue;
        }
        if ($depth > 0 && mb_stripos($part, $anchor) !== false) {
            return true;
        }
    }

    return false;
}

/**
 * Link the first occurrence of $anchor that appears in visible text.
 *
 * Walks the content splitting on tags, so only the text BETWEEN tags is
 * eligible. Skips anything inside <a>, <script>, <style>, <code>, <pre>
 * — linking a word inside a code sample is worse than not linking it.
 *
 * Returns the new content, or null if the anchor never appears in
 * eligible text.
 */
function stb_link_first_text_occurrence(string $content, string $anchor, string $url): ?string
{
    $parts = preg_split('/(<[^>]+>)/', $content, -1, PREG_SPLIT_DELIM_CAPTURE);
    if ($parts === false) {
        return null;
    }

    $skip_depth = 0;
    $skip_tags = ['a', 'script', 'style', 'code', 'pre', 'h1', 'h2', 'h3'];

    foreach ($parts as $i => $part) {
        if ($part === '') {
            continue;
        }
        if ($part[0] === '<') {
            if (preg_match('/^<\s*(\/?)\s*([a-z0-9]+)/i', $part, $m)) {
                $tag = strtolower($m[2]);
                if (in_array($tag, $skip_tags, true)) {
                    $skip_depth += $m[1] === '/' ? -1 : 1;
                    if ($skip_depth < 0) {
                        $skip_depth = 0;
                    }
                }
            }
            continue;
        }
        if ($skip_depth > 0) {
            continue;
        }

        $pos = mb_stripos($part, $anchor);
        if ($pos === false) {
            continue;
        }

        // Preserve the casing actually used in the text.
        $matched = mb_substr($part, $pos, mb_strlen($anchor));
        $replacement = '<a href="' . esc_url($url) . '">' . esc_html($matched) . '</a>';
        $parts[$i] = mb_substr($part, 0, $pos)
            . $replacement
            . mb_substr($part, $pos + mb_strlen($anchor));

        return implode('', $parts);
    }

    return null;
}

// Hook our schema into <head> on relevant pages
add_action('wp_head', function () {
    if (is_singular()) {
        $jsonld = get_post_meta(get_the_ID(), '_stb_schema_jsonld', true);
        if (!empty($jsonld)) {
            // CRITICAL: escape </script> sequences so an attacker who can
            // POST schema JSON-LD can't break out of the <script> block
            // and inject arbitrary JavaScript. The </script> check must
            // be case-insensitive — `</SCRIPT>` also closes the block.
            $safe = preg_replace('#</(script)#i', '<\/$1', $jsonld);
            echo "\n<!-- SEO Tool: schema -->\n<script type=\"application/ld+json\">"
                . $safe
                . "</script>\n";
        }
    }
});

function stb_rest_list_posts(WP_REST_Request $req): WP_REST_Response
{
    $type = sanitize_key($req->get_param('type') ?? 'post');
    $limit = (int)($req->get_param('limit') ?? 50);
    $limit = max(1, min(200, $limit));

    $posts = get_posts([
        'post_type' => $type,
        'post_status' => 'publish',
        'numberposts' => $limit,
        'orderby' => 'modified',
        'order' => 'DESC',
    ]);

    return new WP_REST_Response([
        'ok' => true,
        'count' => count($posts),
        'posts' => array_map(function ($p) {
            return [
                'id' => $p->ID,
                'title' => $p->post_title,
                'permalink' => get_permalink($p->ID),
                'modified' => $p->post_modified,
                'meta_description' => stb_get_meta_description($p->ID),
            ];
        }, $posts),
    ]);
}

function stb_rest_revisions(): WP_REST_Response
{
    $revs = get_option(STB_OPTION_REVISIONS, []);
    return new WP_REST_Response([
        'ok' => true,
        'revisions' => array_slice(array_reverse($revs), 0, 100),
    ]);
}

function stb_rest_undo(WP_REST_Request $req): WP_REST_Response
{
    $rev_id = (int)$req['rev_id'];
    $revs = get_option(STB_OPTION_REVISIONS, []);
    $found = null;
    foreach ($revs as $r) {
        if (($r['rev_id'] ?? 0) === $rev_id) {
            $found = $r;
            break;
        }
    }
    if (!$found) {
        return new WP_REST_Response(['ok' => false, 'error' => 'Revision not found'], 404);
    }

    // "post:123" / "attachment:456". Destructuring this without checking
    // emits an undefined-index warning and then undoes against object 0
    // if the option is ever malformed — hand-edited, half-written by a
    // failed request, or migrated from an older format. Refuse instead:
    // an undo that targets the wrong object is worse than one that
    // doesn't run.
    $bits = explode(':', (string)($found['object'] ?? ''), 2);
    if (count($bits) !== 2 || !ctype_digit($bits[1])) {
        return new WP_REST_Response(
            ['ok' => false, 'error' => 'Revision refers to an object this plugin cannot identify'],
            422,
        );
    }
    $object_id = (int)$bits[1];
    $field = $found['field'];
    $previous = $found['old'];

    switch ($field) {
        case 'title':
            wp_update_post(['ID' => $object_id, 'post_title' => (string)$previous]);
            break;
        case 'meta_description':
            stb_set_meta_description($object_id, (string)$previous);
            break;
        case 'alt':
            update_post_meta($object_id, '_wp_attachment_image_alt', (string)$previous);
            break;
        case 'schema':
            // Undoing "schema was added" means removing it, and the meta
            // is deleted rather than set to '' so it matches what
            // stb_rest_set_schema does with an empty value. An empty
            // string left behind isn't printed — the head filter checks
            // !empty — but it makes the two paths disagree about what
            // "no schema" looks like, and /schema would keep answering
            // as though the plugin still managed the page.
            if ((string)$previous === '') {
                delete_post_meta($object_id, '_stb_schema_jsonld');
            } else {
                update_post_meta($object_id, '_stb_schema_jsonld', (string)$previous);
            }
            break;
        case 'content':
            // Whole-body restore. The link inserter stores the entire
            // previous post_content rather than a diff precisely so this
            // is a straight put-it-back, with no attempt to unpick
            // individual edits — the article returns to exactly what it
            // was, including any hand edits made in the same revision.
            $restored = wp_update_post(
                ['ID' => $object_id, 'post_content' => (string)$previous],
                true,
            );
            if (is_wp_error($restored)) {
                return new WP_REST_Response(
                    ['ok' => false, 'error' => $restored->get_error_message()],
                    500,
                );
            }
            break;
        default:
            return new WP_REST_Response(['ok' => false, 'error' => 'Unsupported field'], 400);
    }

    stb_record_revision($field, $found['object'], $found['new'], $previous);
    return new WP_REST_Response(['ok' => true, 'undone_rev_id' => $rev_id]);
}

/**
 * Resolve a public URL on this WP site to its post / page / CPT id.
 * Falls back through url_to_postid (core), the WP shortlink query, then
 * a manual home-relative path lookup. Returns 404 if nothing matches.
 */
function stb_rest_find_by_url(WP_REST_Request $req): WP_REST_Response
{
    $url = (string)$req->get_param('url');
    if (!$url) {
        return new WP_REST_Response(['error' => 'url required'], 400);
    }

    // Core resolver — handles permalinks, dates, taxonomies.
    $id = url_to_postid($url);
    if ($id > 0) {
        return new WP_REST_Response(['id' => $id]);
    }

    // Try the path relative to home_url (handles language-tagged etc.)
    $home = home_url('/');
    if (str_starts_with($url, $home)) {
        $path = substr($url, strlen($home));
        $maybe = url_to_postid(home_url('/' . ltrim($path, '/')));
        if ($maybe > 0) {
            return new WP_REST_Response(['id' => $maybe]);
        }
    }

    // Last resort: try matching by post_name (slug) of the trailing segment.
    $parts = parse_url($url);
    if (!empty($parts['path'])) {
        $segments = array_filter(explode('/', trim($parts['path'], '/')));
        $slug = end($segments);
        if ($slug) {
            $page = get_page_by_path($slug, OBJECT, ['post', 'page']);
            if ($page) {
                return new WP_REST_Response(['id' => $page->ID]);
            }
        }
    }

    return new WP_REST_Response(['error' => 'not found'], 404);
}

/**
 * Create a new WordPress post. Used by the SEO Tool's daily automation
 * when a blog_draft is approved + published.
 *
 * Body (JSON):
 *   - title           (string, required)
 *   - content         (string, required) — raw HTML
 *   - excerpt         (string, optional)
 *   - status          ("draft" | "publish", default "draft")
 *   - schemaJsonLd    (object | array | null) — saved as _stb_schema_jsonld
 *   - metaDescription (string, optional) — saved via stb_set_meta_description
 */
function stb_rest_create_post(WP_REST_Request $req): WP_REST_Response
{
    $body = $req->get_json_params();
    $title = isset($body['title']) ? sanitize_text_field((string)$body['title']) : '';
    $content = isset($body['content']) ? (string)$body['content'] : '';
    $excerpt = isset($body['excerpt']) ? sanitize_textarea_field((string)$body['excerpt']) : '';
    $status = isset($body['status']) && in_array($body['status'], ['draft', 'publish'], true)
        ? $body['status']
        : 'draft';

    if ($title === '' || $content === '') {
        return new WP_REST_Response(
            ['ok' => false, 'error' => 'title and content are required'],
            400,
        );
    }

    $post_id = wp_insert_post([
        'post_title'   => $title,
        'post_content' => wp_kses_post($content),
        'post_excerpt' => $excerpt,
        'post_status'  => $status,
        'post_type'    => 'post',
    ], true);

    if (is_wp_error($post_id)) {
        return new WP_REST_Response(
            ['ok' => false, 'error' => $post_id->get_error_message()],
            500,
        );
    }

    if (!empty($body['metaDescription'])) {
        stb_set_meta_description($post_id, (string)$body['metaDescription']);
    }
    if (!empty($body['schemaJsonLd'])) {
        update_post_meta(
            $post_id,
            '_stb_schema_jsonld',
            wp_json_encode($body['schemaJsonLd']),
        );
    }

    return new WP_REST_Response([
        'ok'  => true,
        'id'  => $post_id,
        'url' => get_permalink($post_id),
    ]);
}
